### ISSUE TITLE
Consider deleting Move

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL23/solver-dots-and-booxes#8]
https://github.com/TU-CSCI2322-FL23/solver-dots-and-booxes/blob/a02eb65c7cd977c9a92e14019b395904a19dbcd1/DotsAndBoxes.hs#L14C1-L15C1

You can just use LIne instead. You could make it a type alias, but I think Line makes just as much sense.

**Comment by augustryder** [comment]
we are too lazy, made it a newtype instead to increase efficiency at runtime
